blank_issues_enabled: false
contact_links:
  - name: Help / Questions
    url: https://github.com/ietf-tools/datatracker/discussions/categories/help-questions
    about: Need help? Have a question on setting up the project or its usage?
