name: Report a Bug
description: Something isn't right? File a bug report
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Datatracker are you running?
      placeholder: e.g. 7.45.0
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Linux
        - MacOS (arm)
        - MacOS (x64)
        - Windows
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome / Edge
        - Firefox
        - Safari
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the IETF's Code of Conduct
          required: true
