name: Dev PG DB Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-pg:
    name: Build PostgreSQL Docker Images
    runs-on: ubuntu-latest
    container: ghcr.io/ietf-tools/datatracker-app-base:latest
    permissions:
      contents: read
      packages: write
    services:
      db:
        image: ghcr.io/ietf-tools/datatracker-db:latest
        volumes:
            - mariadb-data:/var/lib/mysql
        env:
            MYSQL_ROOT_PASSWORD: ietf
            MYSQL_DATABASE: ietf_utf8
            MYSQL_USER: django
            MYSQL_PASSWORD: RkTkDPFnKpko
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'feat/postgres'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Migrate
        run: |
          chmod +x ./docker/scripts/db-pg-migrate.sh
          sh ./docker/scripts/db-pg-migrate.sh
      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/db-pg.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ietf-tools/datatracker-db-pg:latest
