name: Publish BS3

on:
  push:
    branches: [ main ]
    paths: [ bootstrap/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          
      - name: Set package.json version
        uses: HarmvZ/set-package-json-version-action@v0.1.2
        with:
          version: ${{ env.PKG_VERSION_STRICT }}
          path: ./bootstrap

      - name: Build Release
        working-directory: bootstrap
        run: |
          npm install -g grunt-cli
          npm ci
          grunt dist
          
      - name: Publish to NPM
        run: npm publish --access public
        working-directory: bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: dist
          path: bootstrap/dist
